# Generated by Django 5.0.4 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcribed_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('video_language', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=100)),
                ('video_length', models.IntegerField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('video_text', models.TextField()),
                ('video_transcribe', models.TextField()),
            ],
        ),
    ]
