# Generated by Django 5.0.4 on 2026-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_repair_missing_job_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_material',
            name='native_language',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learning_material',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcribed_video',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcribed_video',
            name='video_language',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transcribed_video',
            name='video_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='learning_material',
            constraint=models.UniqueConstraint(fields=('linked_video', 'native_language'), name='uq_learning_material_video_lang'),
        ),
    ]
